services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - media_volume:/app/media
      - static_volume:/app/static
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    environment:
      - DB_HOST=db
      - DB_NAME=daniyal_damu
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432

  db:
    image: postgres:15.6-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=daniyal_damu
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d daniyal_damu"]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    volumes:
      - media_volume:/usr/share/nginx/html/media
      - static_volume:/usr/share/nginx/html/static

volumes:
  postgres_data:
  media_volume:
  static_volume:
